reference: test_data/ecoli.fa
#reference: test_data/references/ecoli.fa
read_len: 10
coverage: 3
ploidy: 9
paired_ended: true
fragment_mean: 10.0
fragment_st_dev: 11.0
mutation_rate: .

produce_bam: true
produce_vcf: true
produce_fasta: true
produce_fastq: false

overwrite_output: true
output_dir: test_data
output_prefix: testing
