reference: .
read_len: .
coverage: .
mutation_rate: .

ploidy: .
paired_ended: .
fragment_mean: .
fragment_st_dev: .

produce_bam: .
produce_vcf: .
produce_fasta: .
produce_fastq: .

overwrite_output: .
output_dir: .
output_prefix: .