[package]
name = "common-tools"
version = "0.2.0"
authors = ["Joshua Allen <jallen17@illinois.edu>"]
edition = "2021"
license = "LICENSE.md"

[lib]
name = "common"
crate-type = ["lib"]
test = true
path = "src/lib.rs"

[dependencies]
rand = "0.9.0-alpha.1"
rand_core = "0.9.0-alpha.1"
rand_chacha = "0.9.0-alpha.1"
serde = { version = "1.0.197", features = ["derive"] }
log = "0.4.21"