[package]
name = "common"
version = "0.2.0"
authors = ["Joshua Allen <jallen17@illinois.edu>"]

[dependencies]
simple_rng = { path = "../simple_rng" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
log = "0.4.21"
serde_derive = "1.0.197"
