//! This will convert data to a writable form and output the results. Needs some updates to account for the new data structures.
extern crate log;

use std::collections::HashMap;
use std::io::{self, BufReader, Lines, Read};
use std::num::ParseIntError;
use std::path::PathBuf;
use std::io::Write;
use flate2::write::GzEncoder;
use flate2::Compression;
use itertools::Itertools;
use thiserror::Error;
use log::*;

use crate::file_tools::file_io::{create_output_file, read_gzip_lines, read_lines};
use crate::structs::nucleotides::{sequence_array_to_string, Nucleotide};
use crate::structs::mutated_map::MutatedMap;
use crate::structs::variants::{Variant, VariantType};

#[derive(Debug, Error)]
pub enum VcfToolsError {
    #[error("Error reading the vcf file. Check file format: {0}")]
    MalformedVcf(String),
    #[error("IO error from the bed reader: {0}")]
    IoError(#[from] io::Error),
    #[error("Error parsing ints from the bed file: {0}")]
    ParserError(#[from] ParseIntError),
    #[error("File has an unknown or missing file extension: {0}")]
    FileExtensionUnknown(String)
}

pub fn write_vcf(
    mutated_maps: &HashMap<String, Vec<MutatedMap>>,
    contig_order: &Vec<String>,
    fasta_lengths: &HashMap<String, usize>,
    reference_path: &PathBuf,
    overwrite_output: bool,
    output_vcf: &PathBuf,
) -> io::Result<()> {
    // Takes:
    // mutated_maps: A map of contig names keyed to lists of mutated maps holding variants 
    //     in that contig consisting of a tuple of (position, alt base, ref base).
    // fasta_order: A vector of contig names in the order of the reference fasta.
    // faste_lengths: lengths of contigs, required for vcf.
    // reference_path: The location of the reference file this vcf is showing variants from.
    // overwrite output: Whether to overwrite output for the vcf
    // output_vcf: The PathBuf object with the path to the output file
    // Result:
    // Throws and error if there's a problem, or else returns nothing.
    //
    // set the filename of the output vcf
    let outfile = create_output_file(
        output_vcf, 
        overwrite_output
    )?;
    let mut buffer = GzEncoder::new(outfile, Compression::default());
    // add the vcf header
    writeln!(&mut buffer, "##fileformat=VCFv4.1")?;
    writeln!(&mut buffer, "##reference={}", reference_path.display())?;
    for contig in contig_order {
        let length = fasta_lengths[contig];
        writeln!(
            &mut buffer,
            "##contig=<ID={},length={}>",
            &contig,
            length
        )?;
    }
    writeln!(&mut buffer, "##Generated by rusty-neat")?;
    writeln!(&mut buffer, "##ALT=<ID=DEL,Description=\"Deletion\">")?;
    writeln!(
        &mut buffer,
        "##ALT=<ID=INS,Description=\"Insertion of novel sequence\">"
    )?;
    writeln!(
        &mut buffer,
        "##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">"
    )?;
    // Add a neat sample column
    writeln!(
        &mut buffer,
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tNEAT_simulated_sample"
    )?;
    // write out mutations
    for contig in contig_order {
        let block_maps = &mutated_maps[contig];
        for block_map in block_maps {
            for (position, variant) in &block_map.variant_map {
                // Format the output line. Any fields without data will be a simple period. Quality
                // is set to 37 for all these variants, to indicate in the golden vcf that these are
                // the generated variants.
                let line = format!(
                    "{}\t{}\t.\t{}\t{}\t37\tPASS\t.\tGT\t{}",
                    contig,
                    position + 1,
                    sequence_array_to_string(&variant.reference),
                    sequence_array_to_string(&variant.alternate),
                    variant.genotype_str,
                );
                writeln!(&mut buffer, "{}", line)?;
            }
        }
    }
    Ok(())
}

pub fn read_vcf(vcf_file: PathBuf) -> Result<Vec<Variant>, VcfToolsError> {
    let ext = vcf_file.extension();
    match ext {
        Some(ext) => {
            if ext == "gz" {
                return process_gzip_vcf(&vcf_file)
            } else {
                return process_vcf(&vcf_file)
            }
        },
        None => panic!("file extonsion unknown! {:?}", vcf_file),
    }
}

fn process_gzip_vcf(filename: &PathBuf) -> Result<Vec<Variant>, VcfToolsError> {
    let reader = read_gzip_lines(filename)?;
    return Ok(read_open_vcf(reader).expect("Problem processing lines of gzipped bed file"))
}

fn process_vcf(filename: &PathBuf) -> Result<Vec<Variant>, VcfToolsError> {
    let reader = read_lines(filename)?;
    return Ok(read_open_vcf(reader).expect("Error processing bed file"))
}

fn read_open_vcf<P: Read> (reader: Lines<BufReader<P>>) -> Result<Vec<Variant>, VcfToolsError> {
    let mut file_records: Vec<Variant> = Vec::new();
    for result in reader {
        match result {
            Ok(line) => {
                if line.starts_with("#") {
                    continue
                } else {
                    let split_line: Vec<&str> = line.split("\t").collect();
                    let chrom = split_line[0];
                    let pos = split_line[1].parse();
                    let location: usize = {
                        match pos {
                            Ok(num) => num,
                            Err(error) => return Err(VcfToolsError::ParserError(error))
                        }
                    };
                    let id = split_line[2];
                    let vcf_reference = split_line[3];
                    let vcf_alternate = split_line[4];
                    let qual = split_line[5].parse();
                    let quality_score: Option<usize> = {
                        match qual {
                            Ok(num) => Some(num),
                            Err(error) => return Err(VcfToolsError::ParserError(error))
                        }
                    };
                    let filter = split_line[6];
                    let info = split_line[7];
                    let mut format: Vec<String> = Vec::new();
                    let mut sample: Vec<String> = Vec::new();
                    if split_line.len() > 7 {
                        if split_line.len() < 9 {
                            return Err(
                                VcfToolsError::MalformedVcf(
                                "FORMAT field present with no Sample field, invalid VCF".to_string()
                                )
                            )
                        }
                        // This is a FORMAT field, if it exists
                        let format_split: Vec<&str> = split_line[8].split(":").collect();
                        let sample_split: Vec<&str> = split_line[9].split(":").collect();
                        let format_len = format_split.len();
                        if sample_split.len() != format_len {
                            return Err(
                                VcfToolsError::MalformedVcf(
                                    "FORMAT list and sample list different lengths, invalid VCF".to_string()
                                )
                            )
                        }
                        for i in 0..format_len {
                            // Look for GT

                            format.push(format_split[i].to_string());
                            sample.push(sample_split[i].to_string());
                        }
                    }
                    if split_line.len() > 9 {
                        warn!("Currently rneat can only read one sample per record")
                    }
                    


                }
            },
            Err(error) => {
                return Err(VcfToolsError::IoError(error))
            },
        }
    }
    Ok(file_records)
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;
    use crate::structs::{nucleotides::Nucleotide, variants::{Variant, VariantType}};
    use std::fs;

    #[test]
    pub fn test_write_vcf() {
        let variant1 = Variant::new(
            VariantType::SNP,
            3,
            &vec![Nucleotide::A],
            &vec![Nucleotide::G],
            &mut vec![0,1],
        ).unwrap();
        let variant2 = Variant::new(
            VariantType::SNP,
            7,
            &vec![Nucleotide::T],
            &vec![Nucleotide::G],
            &mut vec![1,1],
        ).unwrap();
        let mutated_map = MutatedMap::new(
            PathBuf::from("name_000100_000200.fa"),
            vec![variant1, variant2]
        ).unwrap();
        let mut mutated_maps = HashMap::new();
        mutated_maps.insert("chr1".to_string(), vec![mutated_map]);
        let fasta_order = Vec::from(["chr1".to_string()]);
        let fasta_length = HashMap::from([("chr1".to_string(), 20)]);
        let reference_path = PathBuf::from("test_data/references/H1N1.fa");
        let overwrite_output = false;
        let output_filename = PathBuf::from("good_test.vcf");
        let result = write_vcf(
            &mutated_maps,
            &fasta_order,
            &fasta_length,
            &reference_path,
            overwrite_output,
            &output_filename,
        );
        result.unwrap();
        assert!(Path::new("good_test.vcf").exists());
        fs::remove_file("good_test.vcf").unwrap();
    }
}
