//! This will convert data to a writable form and output the results. Needs some updates to account for the new data structures.
extern crate log;

use flate2::Compression;
use flate2::write::GzEncoder;
use log::*;
use std::collections::HashMap;
use std::io::Write;
use std::io::{self, BufReader, Lines, Read};
use std::num::ParseIntError;
use std::path::PathBuf;
use thiserror::Error;

use crate::file_tools::file_io::{
    create_output_file, is_gzipped_file, read_gzip_lines, read_lines,
};
use crate::structs::mutated_map::MutatedMap;
use crate::structs::nucleotides::sequence_array_to_string;
use crate::structs::variants::{Variant, VariantError};

#[derive(Debug, Error)]
pub enum VcfToolsError {
    #[error("Error reading the vcf file. Check file format: {0}")]
    MalformedVcf(String),
    #[error("IO error from the bed reader: {0}")]
    IoError(#[from] io::Error),
    #[error("Error parsing ints from the bed file: {0}")]
    ParserError(#[from] ParseIntError),
    #[error("File has an unknown or missing file extension: {0}")]
    FileExtensionUnknown(String),
    #[error("Error creating a variant from file: {0}")]
    VariantError(#[from] VariantError),
}

pub fn write_vcf(
    mutated_maps: &HashMap<String, Vec<MutatedMap>>,
    contig_order: &Vec<String>,
    fasta_lengths: &HashMap<String, usize>,
    reference_path: &PathBuf,
    overwrite_output: bool,
    output_vcf: &PathBuf,
) -> io::Result<()> {
    // Takes:
    // mutated_maps: A map of contig names keyed to lists of mutated maps holding variants
    //     in that contig consisting of a tuple of (position, alt base, ref base).
    // fasta_order: A vector of contig names in the order of the reference fasta.
    // faste_lengths: lengths of contigs, required for vcf.
    // reference_path: The location of the reference file this vcf is showing variants from.
    // overwrite output: Whether to overwrite output for the vcf
    // output_vcf: The PathBuf object with the path to the output file
    // Result:
    // Throws and error if there's a problem, or else returns nothing.
    //
    // set the filename of the output vcf
    let outfile = create_output_file(output_vcf, overwrite_output)?;
    let mut buffer = GzEncoder::new(outfile, Compression::default());
    // add the vcf header
    writeln!(&mut buffer, "##fileformat=VCFv4.1")?;
    writeln!(&mut buffer, "##reference={}", reference_path.display())?;
    for contig in contig_order {
        let length = fasta_lengths[contig];
        writeln!(&mut buffer, "##contig=<ID={},length={}>", &contig, length)?;
    }
    writeln!(&mut buffer, "##Generated by rusty-neat")?;
    writeln!(&mut buffer, "##ALT=<ID=DEL,Description=\"Deletion\">")?;
    writeln!(
        &mut buffer,
        "##ALT=<ID=INS,Description=\"Insertion of novel sequence\">"
    )?;
    writeln!(
        &mut buffer,
        "##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">"
    )?;
    // Add a neat sample column
    writeln!(
        &mut buffer,
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tNEAT_simulated_sample"
    )?;
    // write out mutations
    for contig in contig_order {
        let block_maps = &mutated_maps[contig];
        for block_map in block_maps {
            for (position, variant) in &block_map.variant_map {
                // Format the output line. Any fields without data will be a simple period. Quality
                // is set to 37 for all these variants, to indicate in the golden vcf that these are
                // the generated variants.
                let line = format!(
                    "{}\t{}\t.\t{}\t{}\t37\tPASS\t.\tGT\t{}",
                    contig,
                    position + 1,
                    sequence_array_to_string(&variant.reference),
                    sequence_array_to_string(&variant.alternate),
                    variant.genotype_str,
                );
                writeln!(&mut buffer, "{}", line)?;
            }
        }
    }
    Ok(())
}

pub fn read_vcf(vcf_file: PathBuf) -> Result<HashMap<String, Vec<Variant>>, VcfToolsError> {
    if is_gzipped_file(&vcf_file)? {
        process_gzip_vcf(&vcf_file)
    } else {
        process_vcf(&vcf_file)
    }
}

fn process_gzip_vcf(filename: &PathBuf) -> Result<HashMap<String, Vec<Variant>>, VcfToolsError> {
    let reader = read_gzip_lines(filename)?;
    read_open_vcf(reader)
}

fn process_vcf(filename: &PathBuf) -> Result<HashMap<String, Vec<Variant>>, VcfToolsError> {
    let reader = read_lines(filename)?;
    read_open_vcf(reader)
}

fn read_open_vcf<P: Read>(
    reader: Lines<BufReader<P>>,
) -> Result<HashMap<String, Vec<Variant>>, VcfToolsError> {
    let mut file_records: HashMap<String, Vec<Variant>> = HashMap::new();
    for result in reader {
        match result {
            Ok(line) => {
                if line.starts_with("#") {
                    continue;
                } else {
                    let split_line: Vec<&str> = line.split("\t").collect();
                    let chrom = split_line[0];
                    let pos = split_line[1].parse();
                    let location: usize = {
                        match pos {
                            Ok(num) => num,
                            Err(error) => return Err(VcfToolsError::ParserError(error)),
                        }
                    };
                    let id = split_line[2];
                    let vcf_reference = split_line[3];
                    let vcf_alternate = split_line[4];
                    if vcf_alternate.contains(',') {
                        debug!("Skipping multi-allelic site at {}:{}", chrom, location);
                        continue;
                    }
                    // QUAL may be "." in real-world VCFs
                    let quality_score: usize = split_line[5].parse().unwrap_or(0);
                    let filter = split_line[6];
                    let info_field = split_line[7];
                    let mut format: Vec<String> = Vec::new();
                    let mut sample: Vec<String> = Vec::new();
                    if split_line.len() > 8 {
                        let fmt = split_line[8];
                        let smp = split_line[9];
                        // "." means no FORMAT/SAMPLE data — GT will be absent and cause an error below
                        if fmt != "." && smp != "." {
                            let format_split: Vec<&str> = fmt.split(":").collect();
                            let sample_split: Vec<&str> = smp.split(":").collect();
                            let format_len = format_split.len();
                            if sample_split.len() != format_len {
                                return Err(VcfToolsError::MalformedVcf(
                                    "FORMAT list and sample list different lengths, invalid VCF"
                                        .to_string(),
                                ));
                            }
                            for i in 0..format_len {
                                format.push(format_split[i].to_string());
                                sample.push(sample_split[i].to_string());
                            }
                        }
                    }
                    if split_line.len() > 10 {
                        warn!("Currently rneat can only read one sample per record")
                    }
                    let variant = match Variant::from_file(
                        location,
                        id,
                        filter,
                        info_field,
                        vcf_reference,
                        vcf_alternate,
                        quality_score,
                        format,
                        sample,
                    ) {
                        Ok(v) => v,
                        Err(e) => {
                            warn!("Skipping variant at {}:{} — {}", chrom, location, e);
                            continue;
                        }
                    };
                    // Standard hashmap safety check
                    if !file_records.contains_key(chrom) {
                        file_records.insert(chrom.to_string(), Vec::new());
                    }
                    file_records.get_mut(chrom).unwrap().push(variant);
                }
            }
            Err(error) => return Err(VcfToolsError::IoError(error)),
        }
    }
    Ok(file_records)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::structs::{
        nucleotides::Nucleotide,
        variants::{Variant, VariantType},
    };
    use std::io::Write;

    #[test]
    pub fn test_write_vcf() {
        let temp_dir = tempfile::tempdir().unwrap();
        let variant1 = Variant::new(
            VariantType::SNP,
            3,
            &vec![Nucleotide::A],
            &vec![Nucleotide::G],
            &mut vec![0, 1],
        )
        .unwrap();
        let variant2 = Variant::new(
            VariantType::SNP,
            7,
            &vec![Nucleotide::T],
            &vec![Nucleotide::G],
            &mut vec![1, 1],
        )
        .unwrap();
        let mutated_map = MutatedMap::from_interval(100, 200, vec![variant1, variant2]).unwrap();
        let mut mutated_maps = HashMap::new();
        mutated_maps.insert("chr1".to_string(), vec![mutated_map]);
        let fasta_order = Vec::from(["chr1".to_string()]);
        let fasta_length = HashMap::from([("chr1".to_string(), 20)]);
        let reference_path = PathBuf::from("test_data/references/H1N1.fa");
        let output_filename = temp_dir.path().join("good_test.vcf");
        let result = write_vcf(
            &mutated_maps,
            &fasta_order,
            &fasta_length,
            &reference_path,
            false,
            &output_filename,
        );
        result.unwrap();
        assert!(output_filename.exists());

        // Read back and verify content
        let lines: Vec<String> = crate::file_tools::file_io::read_gzip_lines(&output_filename)
            .unwrap()
            .map(|l| l.unwrap())
            .collect();

        // Header lines must be present
        assert!(lines.iter().any(|l| l == "##fileformat=VCFv4.1"));
        assert!(
            lines
                .iter()
                .any(|l| l.contains("##contig=<ID=chr1,length=20>"))
        );
        assert!(
            lines
                .iter()
                .any(|l| l.contains("##Generated by rusty-neat"))
        );
        assert!(
            lines
                .iter()
                .any(|l| l.contains("#CHROM\tPOS\tID\tREF\tALT"))
        );

        // Both variant lines must be present (HashMap iteration order is non-deterministic)
        assert!(
            lines
                .iter()
                .any(|l| l == "chr1\t4\t.\tA\tG\t37\tPASS\t.\tGT\t0/1"),
            "missing het SNP line; got: {:?}",
            lines
        );
        assert!(
            lines
                .iter()
                .any(|l| l == "chr1\t8\t.\tT\tG\t37\tPASS\t.\tGT\t1/1"),
            "missing hom SNP line; got: {:?}",
            lines
        );
    }

    #[test]
    pub fn test_write_vcf_multi_contig() {
        let temp_dir = tempfile::tempdir().unwrap();

        let map1 = MutatedMap::from_interval(
            100,
            200,
            vec![
                Variant::new(
                    VariantType::SNP,
                    5,
                    &vec![Nucleotide::A],
                    &vec![Nucleotide::C],
                    &mut vec![0, 1],
                )
                .unwrap(),
            ],
        )
        .unwrap();
        let map2 = MutatedMap::from_interval(
            100,
            200,
            vec![
                Variant::new(
                    VariantType::SNP,
                    10,
                    &vec![Nucleotide::G],
                    &vec![Nucleotide::T],
                    &mut vec![1, 1],
                )
                .unwrap(),
            ],
        )
        .unwrap();

        let mut mutated_maps = HashMap::new();
        mutated_maps.insert("chr1".to_string(), vec![map1]);
        mutated_maps.insert("chr2".to_string(), vec![map2]);

        let contig_order = vec!["chr1".to_string(), "chr2".to_string()];
        let fasta_lengths = HashMap::from([
            ("chr1".to_string(), 300usize),
            ("chr2".to_string(), 500usize),
        ]);

        let output_path = temp_dir.path().join("multi_contig.vcf");
        write_vcf(
            &mutated_maps,
            &contig_order,
            &fasta_lengths,
            &PathBuf::from("ref.fa"),
            false,
            &output_path,
        )
        .unwrap();

        let lines: Vec<String> = crate::file_tools::file_io::read_gzip_lines(&output_path)
            .unwrap()
            .map(|l| l.unwrap())
            .collect();

        // Both contigs must appear in the header
        assert!(
            lines
                .iter()
                .any(|l| l.contains("##contig=<ID=chr1,length=300>"))
        );
        assert!(
            lines
                .iter()
                .any(|l| l.contains("##contig=<ID=chr2,length=500>"))
        );

        // Variant lines for both contigs must be present
        assert!(
            lines.iter().any(|l| l.starts_with("chr1\t6\t")),
            "missing chr1 variant; got: {:?}",
            lines
        );
        assert!(
            lines.iter().any(|l| l.starts_with("chr2\t11\t")),
            "missing chr2 variant; got: {:?}",
            lines
        );
    }

    #[test]
    fn test_read_vcf_qual_dot() {
        let vcf_content = "\
##fileformat=VCFv4.1\n\
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n\
chr1\t100\t.\tA\tT\t.\tPASS\t.\tGT\t0/1\n";
        let mut tmp = tempfile::Builder::new().suffix(".vcf").tempfile().unwrap();
        write!(tmp, "{}", vcf_content).unwrap();
        let result = read_vcf(tmp.path().to_path_buf());
        assert!(result.is_ok(), "Expected Ok, got {:?}", result);
        let records = result.unwrap();
        let variants = records.get("chr1").expect("chr1 not found");
        assert_eq!(variants.len(), 1);
        assert_eq!(variants[0].quality_score, Some(0));
    }

    #[test]
    fn test_read_vcf_multi_allelic_alt_skipped() {
        // Multi-allelic records (ALT field containing ',') are explicitly skipped
        // by the parser. This test locks in that contract.
        let vcf_content = "\
##fileformat=VCFv4.1\n\
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n\
chr1\t100\t.\tA\tT,C\t60\tPASS\t.\tGT\t1|2\n\
chr1\t200\t.\tG\tC\t60\tPASS\t.\tGT\t0/1\n";
        let mut tmp = tempfile::Builder::new().suffix(".vcf").tempfile().unwrap();
        write!(tmp, "{}", vcf_content).unwrap();
        let records = read_vcf(tmp.path().to_path_buf()).unwrap();
        let variants = records.get("chr1").expect("chr1 not found");
        assert_eq!(
            variants.len(),
            1,
            "multi-allelic record should be skipped; only the simple SNP at 200 should remain",
        );
        assert_eq!(variants[0].location, 200);
    }

    #[test]
    fn test_read_vcf_structural_variant_alt_parses_without_panic() {
        // `<DEL>`-style ALT strings aren't bcf-style SVs we know how to simulate; today the
        // parser doesn't filter them, so each `<`/`D`/`E`/`L`/`>` char becomes Nucleotide::N
        // and the record is stored as an Insertion-typed variant. We don't endorse that — but
        // we lock in "doesn't panic" so future stricter handling is an explicit choice, not a
        // silent regression.
        let vcf_content = "\
##fileformat=VCFv4.1\n\
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n\
chr1\t100\t.\tA\t<DEL>\t60\tPASS\tSVTYPE=DEL;END=200\tGT\t0/1\n";
        let mut tmp = tempfile::Builder::new().suffix(".vcf").tempfile().unwrap();
        write!(tmp, "{}", vcf_content).unwrap();
        let result = read_vcf(tmp.path().to_path_buf());
        assert!(
            result.is_ok(),
            "SV ALT must not error the whole parse: {:?}",
            result
        );
    }

    #[test]
    fn test_read_vcf_info_with_embedded_semicolons_preserved() {
        // INFO is split only on \t, so embedded ';' in the INFO column should not corrupt
        // downstream fields (FORMAT and SAMPLE). Lock in the round-trip.
        let info = "DESC=\"contains;semis\";END=300;NS=1";
        let vcf_content = format!(
            "##fileformat=VCFv4.1\n\
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n\
chr1\t100\t.\tA\tT\t60\tPASS\t{}\tGT\t0/1\n",
            info,
        );
        let mut tmp = tempfile::Builder::new().suffix(".vcf").tempfile().unwrap();
        write!(tmp, "{}", vcf_content).unwrap();
        let records = read_vcf(tmp.path().to_path_buf()).unwrap();
        let variants = records.get("chr1").unwrap();
        assert_eq!(variants.len(), 1);
        // The INFO column survives intact; GT (in SAMPLE column) is unaffected.
        assert_eq!(variants[0].info.as_deref(), Some(info));
    }

    #[test]
    fn test_read_vcf_gzipped_input() {
        // A gzipped VCF (.vcf.gz) should be parsed identically to the plain version.
        let vcf_content = "\
##fileformat=VCFv4.1\n\
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n\
chr1\t100\t.\tA\tT\t60\tPASS\t.\tGT\t0/1\n\
chr2\t250\t.\tG\tC\t60\tPASS\t.\tGT\t1|1\n";

        let temp_dir = tempfile::tempdir().unwrap();
        let path = temp_dir.path().join("input.vcf.gz");
        let f = std::fs::File::create(&path).unwrap();
        let mut encoder = GzEncoder::new(f, Compression::default());
        encoder.write_all(vcf_content.as_bytes()).unwrap();
        encoder.finish().unwrap();

        let records = read_vcf(path).unwrap();
        assert_eq!(records.get("chr1").unwrap().len(), 1);
        assert_eq!(records.get("chr2").unwrap().len(), 1);
    }

    #[test]
    fn test_read_vcf_all_dot_genotype_treated_as_homozygous() {
        // Today `gt_from_str` returns Homozygous when no allele parses as zero — `./.` falls
        // into that bucket. This is arguably a bug (missing GT is not homozygous), but the
        // test pins the current behavior so any future fix is a deliberate, reviewed change.
        use crate::structs::variants::Genotype;
        let vcf_content = "\
##fileformat=VCFv4.1\n\
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n\
chr1\t100\t.\tA\tT\t60\tPASS\t.\tGT\t./.\n";
        let mut tmp = tempfile::Builder::new().suffix(".vcf").tempfile().unwrap();
        write!(tmp, "{}", vcf_content).unwrap();
        let records = read_vcf(tmp.path().to_path_buf()).unwrap();
        let variants = records.get("chr1").unwrap();
        assert_eq!(variants.len(), 1);
        assert!(matches!(variants[0].genotype, Genotype::Homozygous));
    }

    #[test]
    fn test_read_vcf_mixed_phased_unphased_gt_both_supported() {
        // Both `0|1` (phased) and `0/1` (unphased) must parse and yield the same genotype.
        let vcf_content = "\
##fileformat=VCFv4.1\n\
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n\
chr1\t100\t.\tA\tT\t60\tPASS\t.\tGT\t0/1\n\
chr1\t200\t.\tG\tC\t60\tPASS\t.\tGT\t0|1\n";
        let mut tmp = tempfile::Builder::new().suffix(".vcf").tempfile().unwrap();
        write!(tmp, "{}", vcf_content).unwrap();
        use crate::structs::variants::Genotype;
        let records = read_vcf(tmp.path().to_path_buf()).unwrap();
        let variants = records.get("chr1").unwrap();
        assert_eq!(variants.len(), 2);
        assert!(matches!(variants[0].genotype, Genotype::Heterozygous));
        assert!(matches!(variants[1].genotype, Genotype::Heterozygous));
        // Both genotype strings are stored verbatim (not normalized).
        assert_eq!(variants[0].genotype_str, "0/1");
        assert_eq!(variants[1].genotype_str, "0|1");
    }

    #[test]
    fn test_read_vcf_missing_gt_skips_variant() {
        // Variants without GT in FORMAT are skipped with a warning (not a hard error)
        // so that real-world VCFs with mixed FORMAT fields can still be processed.
        let vcf_content = "\
##fileformat=VCFv4.1\n\
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n\
chr1\t100\t.\tA\tT\t60\tPASS\t.\tDP:GQ\t30:99\n";
        let mut tmp = tempfile::Builder::new().suffix(".vcf").tempfile().unwrap();
        write!(tmp, "{}", vcf_content).unwrap();
        let result = read_vcf(tmp.path().to_path_buf());
        assert!(result.is_ok(), "Expected Ok (skip), got {:?}", result);
        assert!(result.unwrap().is_empty(), "Expected no variants parsed");
    }
}
