name: rusty-neat-tests

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/develop_tests" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4.0.1
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ubuntu-latest-cargo-
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose --workspace
